using System.CodeDom.Compiler;

namespace UnambitiousFx.Core.CodeGen.Design;

/// <summary>
/// Represents a file writer that generates C# code files with specified namespaces, usings, and type definitions.
/// </summary>
public sealed class FileWriter {
    private readonly string                      _namespace;
    private readonly List<ITypeDefinitionWriter> _typeBuilders;
    private readonly bool                        _useNullable;
    private readonly List<string>                _usings;

    /// <summary>
    /// Initializes a new instance of the <see cref="FileWriter"/> class.
    /// </summary>
    /// <param name="namespace">The namespace for the generated file.</param>
    /// <param name="typeBuilders">Optional collection of type definition writers to include in the file.</param>
    /// <param name="useNullable">Indicates whether nullable reference types should be enabled in the generated file.</param>
    public FileWriter(string                              @namespace,
                      IEnumerable<ITypeDefinitionWriter>? typeBuilders = null,
                      bool                                useNullable  = true) {
        _namespace   = @namespace;
        _useNullable = useNullable;
        _typeBuilders = typeBuilders is not null
                            ? typeBuilders.ToList()
                            : [];
        _usings = [];
    }

    /// <summary>
    /// Adds a class definition to the file writer.
    /// </summary>
    /// <param name="class">The class writer to add.</param>
    /// <returns>The current <see cref="FileWriter"/> instance.</returns>
    public FileWriter AddClass(ClassWriter @class) {
        _typeBuilders.Add(@class);
        return this;
    }

    /// <summary>
    /// Writes the generated code to the specified <see cref="IndentedTextWriter"/>.
    /// </summary>
    /// <param name="writer">The writer to output the generated code.</param>
    public void Write(IndentedTextWriter writer) {
        WriteHeader(writer);

        if (_useNullable) {
            writer.WriteLine("#nullable enable");
            writer.WriteLine();
        }

        var usings = _typeBuilders.SelectMany(x => x.Usings)
                                  .Concat(_usings)
                                  .Distinct()
                                  .Order();

        foreach (var @using in usings) {
            writer.WriteLine($"using {@using};");
        }

        writer.WriteLine();
        writer.WriteLine($"namespace {_namespace};");
        writer.WriteLine();

        foreach (var typeBuilder in _typeBuilders) {
            typeBuilder.Write(writer);
        }
    }

    /// <summary>
    /// Adds a using directive to the file writer.
    /// </summary>
    /// <param name="using">The namespace to add as a using directive.</param>
    public void AddUsing(string @using) {
        _usings.Add(@using);
    }

    /// <summary>
    /// Writes the auto-generated file header to the specified <see cref="IndentedTextWriter"/>.
    /// </summary>
    /// <param name="writer">The writer to output the header.</param>
    private static void WriteHeader(IndentedTextWriter writer) {
        writer.WriteLine("// <auto-generated>");
        writer.WriteLine("//     This code was generated by UnambitiousFx.Core.CodeGen.");
        writer.WriteLine("//");
        writer.WriteLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        writer.WriteLine("//     the code is regenerated.");
        writer.WriteLine("// </auto-generated>");
        writer.WriteLine();
    }
}
