using System.CodeDom.Compiler;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace UnambitiousFx.Core.Generator;

internal sealed class ResultMapExtensionsFactory(string @namespace,
                                                 ushort maxOfParameters) {
    public SourceText GenerateTask() {
        return GenerateAsync("Task", "Tasks");
    }

    public SourceText GenerateValueTask() {
        return GenerateAsync("ValueTask", "ValueTasks");
    }

    private SourceText GenerateAsync(string taskKeyWork,
                                     string subNamespace) {
        using var sw = new StringWriter();
        using var tw = new IndentedTextWriter(sw);

        tw.WriteLine("// <auto-generated />");
        tw.WriteLine("#nullable enable");
        tw.WriteLine($"namespace {@namespace}.{subNamespace};");

        tw.WriteLine("public static partial class ResultExtensions");
        tw.WriteLine("{");
        tw.Indent++;

        foreach (ushort i in Enumerable.Range(1, maxOfParameters)) {
            if (i == 1) {
                tw.WriteLine($"public static {taskKeyWork}<Result<TOut>> MapAsync<TValue, TOut>(this Result<TValue> result, Func<TValue, {taskKeyWork}<TOut>> map)");
                tw.Indent++;
                tw.WriteLine("where TValue : notnull");
                tw.WriteLine("where TOut : notnull");
                tw.Indent--;
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine("");
                tw.WriteLine("return result.BindAsync(async value =>");
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine("var newValue = await map(value);");
                tw.WriteLine("return Result.Success(newValue);");
                tw.Indent--;
                tw.WriteLine("});");
                tw.Indent--;
                tw.WriteLine("}");
                tw.WriteLine();
                tw.WriteLine(
                    $"public static {taskKeyWork}<Result<TOut>> MapAsync<TValue, TOut>(this {taskKeyWork}<Result<TValue>> awaitableResult, Func<TValue, {taskKeyWork}<TOut>> map)");
                tw.Indent++;
                tw.WriteLine("where TValue : notnull");
                tw.WriteLine("where TOut : notnull");
                tw.Indent--;
                tw.WriteLine("{");
                tw.Indent++;

                tw.WriteLine("return awaitableResult.BindAsync(async value =>");
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine("var newValue = await map(value);");
                tw.WriteLine("return Result.Success(newValue);");
                tw.Indent--;
                tw.WriteLine("});");

                tw.Indent--;
                tw.WriteLine("}");
            }
            else {
                var genericInputParameters = string.Join(", ", Enumerable.Range(1, i)
                                                                         .Select(x => $"TValue{x}"));
                var genericOutputParameters = string.Join(", ", Enumerable.Range(1, i)
                                                                          .Select(x => $"TOut{x}"));
                var callParameters = string.Join(", ", Enumerable.Range(1, i)
                                                                 .Select(x => $"value{x}"));
                var callTupleParameters = string.Join(", ", Enumerable.Range(1, i)
                                                                      .Select(x => $"items.Item{x}"));
                tw.WriteLine(
                    $"public static {taskKeyWork}<Result<{genericOutputParameters}>> Map<{genericInputParameters}, {genericOutputParameters}>(this Result<{genericInputParameters}> result, Func<{genericInputParameters}, {taskKeyWork}<({genericOutputParameters})>> map)");
                tw.Indent++;
                foreach (var genericInputParameter in genericInputParameters.Split(", ".ToCharArray())
                                                                            .Concat(genericOutputParameters.Split(", ".ToCharArray()))
                                                                            .Where(x => !string.IsNullOrWhiteSpace(x))) {
                    tw.WriteLine($"where {genericInputParameter} : notnull");
                }

                tw.Indent--;
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine($"return result.BindAsync(async ({callParameters}) =>");
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine($"var items = await map({callParameters});");
                tw.WriteLine($"return Result.Success({callTupleParameters});");
                tw.Indent--;
                tw.WriteLine("});");

                tw.Indent--;
                tw.WriteLine("}");
                tw.WriteLine();
                tw.WriteLine(
                    $"public static {taskKeyWork}<Result<{genericOutputParameters}>> Map<{genericInputParameters}, {genericOutputParameters}>(this {taskKeyWork}<Result<{genericInputParameters}>> awaitableResult, Func<{genericInputParameters}, {taskKeyWork}<({genericOutputParameters})>> map)");
                tw.Indent++;
                foreach (var genericInputParameter in genericInputParameters.Split(", ".ToCharArray())
                                                                            .Concat(genericOutputParameters.Split(", ".ToCharArray()))
                                                                            .Where(x => !string.IsNullOrWhiteSpace(x))) {
                    tw.WriteLine($"where {genericInputParameter} : notnull");
                }

                tw.Indent--;
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine($"return awaitableResult.BindAsync(async ({callParameters}) =>");
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine("var result = await awaitableResult;");
                tw.WriteLine($"var items = await map({callParameters});");
                tw.WriteLine($"return Result.Success({callTupleParameters});");
                tw.Indent--;
                tw.WriteLine("});");

                tw.Indent--;
                tw.WriteLine("}");
            }
        }

        tw.Indent--;
        tw.WriteLine("}");

        return SourceText.From(sw.ToString(), Encoding.UTF8);
    }

    public SourceText Generate() {
        using var sw = new StringWriter();
        using var tw = new IndentedTextWriter(sw);

        tw.WriteLine("// <auto-generated />");
        tw.WriteLine("#nullable enable");
        tw.WriteLine($"namespace {@namespace};");

        tw.WriteLine("public static partial class ResultExtensions");
        tw.WriteLine("{");
        tw.Indent++;

        foreach (ushort i in Enumerable.Range(1, maxOfParameters)) {
            if (i == 1) {
                tw.WriteLine("public static Result<TOut> Map<TValue, TOut>(this Result<TValue> result, Func<TValue, TOut> map)");
                tw.Indent++;
                tw.WriteLine("where TValue : notnull");
                tw.WriteLine("where TOut : notnull");
                tw.Indent--;
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine("return result.Bind(value => Result.Success(map(value)));");
                tw.Indent--;
                tw.WriteLine("}");
            }
            else {
                var genericInputParameters = string.Join(", ", Enumerable.Range(1, i)
                                                                         .Select(x => $"TValue{x}"));
                var genericOutputParameters = string.Join(", ", Enumerable.Range(1, i)
                                                                          .Select(x => $"TOut{x}"));
                var callParameters = string.Join(", ", Enumerable.Range(1, i)
                                                                 .Select(x => $"value{x}"));
                var callTupleParameters = string.Join(", ", Enumerable.Range(1, i)
                                                                      .Select(x => $"items.Item{x}"));
                tw.WriteLine(
                    $"public static Result<{genericOutputParameters}> Map<{genericInputParameters}, {genericOutputParameters}>(this Result<{genericInputParameters}> result, Func<{genericInputParameters}, ({genericOutputParameters})> map)");
                tw.Indent++;
                foreach (var genericInputParameter in genericInputParameters.Split(", ".ToCharArray())
                                                                            .Concat(genericOutputParameters.Split(", ".ToCharArray()))
                                                                            .Where(x => !string.IsNullOrWhiteSpace(x))) {
                    tw.WriteLine($"where {genericInputParameter} : notnull");
                }

                tw.Indent--;
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine($"return result.Bind<{genericInputParameters}, {genericOutputParameters}>(({callParameters}) =>");
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine($"var items = map({callParameters});");
                tw.WriteLine($"return Result.Success<{genericOutputParameters}>({callTupleParameters});");
                tw.Indent--;
                tw.WriteLine("});");

                tw.Indent--;
                tw.WriteLine("}");
            }
        }

        tw.Indent--;
        tw.WriteLine("}");

        return SourceText.From(sw.ToString(), Encoding.UTF8);
    }
}
