using System.CodeDom.Compiler;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace UnambitiousFx.Core.Generator;

internal sealed class ResultTapExtensionsFactory(string @namespace,
                                                 ushort maxOfParameters) {
    public SourceText GenerateTask() {
        return GenerateAsync("Task", "Tasks");
    }

    public SourceText GenerateValueTask() {
        return GenerateAsync("ValueTask", "ValueTasks");
    }

    private SourceText GenerateAsync(string taskKeyWork,
                                     string subNamespace) {
        using var sw = new StringWriter();
        using var tw = new IndentedTextWriter(sw);

        tw.WriteLine("// <auto-generated />");
        tw.WriteLine("#nullable enable");
        tw.WriteLine($"namespace {@namespace}.{subNamespace};");

        tw.WriteLine("public static partial class ResultExtensions");
        tw.WriteLine("{");
        tw.Indent++;

        foreach (ushort i in Enumerable.Range(1, maxOfParameters)) {
            if (i == 1) {
                tw.WriteLine($"public static {taskKeyWork}<Result<TValue>> TapAsync<TValue>(this Result<TValue> result, Func<TValue, {taskKeyWork}> tap)");
                tw.Indent++;
                tw.WriteLine("where TValue : notnull");
                tw.Indent--;
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine("");
                tw.WriteLine("return result.BindAsync(async value =>");
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine("await tap(value);");
                tw.WriteLine("return Result.Success(value);");
                tw.Indent--;
                tw.WriteLine("});");
                tw.Indent--;
                tw.WriteLine("}");
                tw.WriteLine();
                tw.WriteLine(
                    $"public static {taskKeyWork}<Result<TValue>> TapAsync<TValue>(this {taskKeyWork}<Result<TValue>> awaitableResult, Func<TValue, {taskKeyWork}> tap)");
                tw.Indent++;
                tw.WriteLine("where TValue : notnull");
                tw.Indent--;
                tw.WriteLine("{");
                tw.Indent++;

                tw.WriteLine("return awaitableResult.BindAsync(async value =>");
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine("await tap(value);");
                tw.WriteLine("return Result.Success(value);");
                tw.Indent--;
                tw.WriteLine("});");

                tw.Indent--;
                tw.WriteLine("}");
            }
            else {
                var genericInputParameters = string.Join(", ", Enumerable.Range(1, i)
                                                                         .Select(x => $"TValue{x}"));
                var callParameters = string.Join(", ", Enumerable.Range(1, i)
                                                                 .Select(x => $"value{x}"));
                tw.WriteLine(
                    $"public static {taskKeyWork}<Result<{genericInputParameters}>> TapAsync<{genericInputParameters}>(this Result<{genericInputParameters}> result, Func<{genericInputParameters}, {taskKeyWork}> tap)");
                tw.Indent++;
                foreach (var genericInputParameter in genericInputParameters.Split(", ".ToCharArray())
                                                                            .Where(x => !string.IsNullOrWhiteSpace(x))) {
                    tw.WriteLine($"where {genericInputParameter} : notnull");
                }

                tw.Indent--;
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine($"return result.BindAsync(async ({callParameters}) =>");
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine($"await tap({callParameters});");
                tw.WriteLine($"return Result.Success({callParameters});");
                tw.Indent--;
                tw.WriteLine("});");
                tw.Indent--;
                tw.WriteLine("}");
                tw.WriteLine();
                tw.WriteLine(
                    $"public static {taskKeyWork}<Result<{genericInputParameters}>> TapAsync<{genericInputParameters}>(this {taskKeyWork}<Result<{genericInputParameters}>> awaitableResult, Func<{genericInputParameters}, {taskKeyWork}> tap)");
                tw.Indent++;
                foreach (var genericInputParameter in genericInputParameters.Split(", ".ToCharArray())
                                                                            .Where(x => !string.IsNullOrWhiteSpace(x))) {
                    tw.WriteLine($"where {genericInputParameter} : notnull");
                }

                tw.Indent--;
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine($"return awaitableResult.BindAsync(async ({callParameters}) =>");
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine("var result = await awaitableResult;");
                tw.WriteLine($"await tap({callParameters});");
                tw.WriteLine($"return Result.Success({callParameters});");
                tw.Indent--;
                tw.WriteLine("});");

                tw.Indent--;
                tw.WriteLine("}");
            }
        }

        tw.Indent--;
        tw.WriteLine("}");
        return SourceText.From(sw.ToString(), Encoding.UTF8);
    }

    public SourceText Generate() {
        using var sw = new StringWriter();
        using var tw = new IndentedTextWriter(sw);

        tw.WriteLine("// <auto-generated />");
        tw.WriteLine("#nullable enable");
        tw.WriteLine($"namespace {@namespace};");

        tw.WriteLine("public static partial class ResultExtensions");
        tw.WriteLine("{");
        tw.Indent++;
        foreach (ushort i in Enumerable.Range(1, maxOfParameters)) {
            if (i == 1) {
                tw.WriteLine($"public static Result<TValue> Tap<TValue>(this Result<TValue> result, Action<TValue> tap)");
                tw.Indent++;
                tw.WriteLine("where TValue : notnull");
                tw.Indent--;
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine("");
                tw.WriteLine("return result.Bind(value =>");
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine("tap(value);");
                tw.WriteLine("return Result.Success<TValue>(value);");
                tw.Indent--;
                tw.WriteLine("});");
                tw.Indent--;
                tw.WriteLine("}");
                tw.WriteLine();
            }
            else {
                var genericInputParameters = string.Join(", ", Enumerable.Range(1, i)
                                                                         .Select(x => $"TValue{x}"));
                var callParameters = string.Join(", ", Enumerable.Range(1, i)
                                                                 .Select(x => $"value{x}"));
                tw.WriteLine(
                    $"public static Result<{genericInputParameters}> Tap<{genericInputParameters}>(this Result<{genericInputParameters}> result, Action<{genericInputParameters}> tap)");
                tw.Indent++;
                foreach (var genericInputParameter in genericInputParameters.Split(", ".ToCharArray())
                                                                            .Where(x => !string.IsNullOrWhiteSpace(x))) {
                    tw.WriteLine($"where {genericInputParameter} : notnull");
                }

                tw.Indent--;
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine($"return result.Bind(({callParameters}) =>");
                tw.WriteLine("{");
                tw.Indent++;
                tw.WriteLine($"tap({callParameters});");
                tw.WriteLine($"return Result.Success<{genericInputParameters}>({callParameters});");
                tw.Indent--;
                tw.WriteLine("});");
                tw.Indent--;
                tw.WriteLine("}");
                tw.WriteLine();
            }
        }

        tw.Indent--;
        tw.WriteLine("}");

        return SourceText.From(sw.ToString(), Encoding.UTF8);
    }
}
