using System.CodeDom.Compiler;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace UnambitiousFx.Core.Generator;

internal sealed class ResultValueOrExtensionsFactory(string @namespace, ushort maxOfParameters)
{
    public SourceText GenerateTask() => GenerateAsync("Task", "Tasks",
        (genericOut, failureExpr) => $"Task.FromResult<{genericOut}>({failureExpr})");
    public SourceText GenerateValueTask() => GenerateAsync("ValueTask", "ValueTasks",
        (genericOut, failureExpr) => $"new ValueTask<{genericOut}>({failureExpr})");

    private SourceText GenerateAsync(string taskKeyword, string subNamespace, Func<string,string,string> wrapFailure)
    {
        using var sw = new StringWriter();
        using var tw = new IndentedTextWriter(sw);
        tw.WriteLine("// <auto-generated />");
        tw.WriteLine("#nullable enable");
        tw.WriteLine($"namespace {@namespace}.{subNamespace};");
        tw.WriteLine();
        tw.WriteLine("public static partial class ResultExtensions");
        tw.WriteLine("{");
        tw.Indent++;
        foreach (ushort arity in Enumerable.Range(1, maxOfParameters))
        {
            var genericIn = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"TValue{i}"));
            var constraints = string.Join(" ", Enumerable.Range(1, arity).Select(i => $"where TValue{i} : notnull"));
            var callParams = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"value{i}"));
            var outType = arity == 1 ? "TValue1" : $"({string.Join(", ", Enumerable.Range(1, arity).Select(i => $"TValue{i}"))})";
            var successExpr = arity == 1 ? "value1" : $"({callParams})";
            var fallbackParamType = arity == 1 ? "TValue1 fallback" : $"({string.Join(", ", Enumerable.Range(1, arity).Select(i => $"TValue{i}"))}) fallback";
            var fallbackFactoryType = arity == 1 ? "Func<TValue1> fallbackFactory" : $"Func<{outType}> fallbackFactory";
            // Constant fallback
            tw.WriteLine($"public static async {taskKeyword}<{outType}> ValueOr<{genericIn}>(this {taskKeyword}<Result<{genericIn}>> awaitableResult, {fallbackParamType}) {constraints}");
            tw.WriteLine("{");
            tw.Indent++;
            tw.WriteLine("var result = await awaitableResult.ConfigureAwait(false);");
            tw.WriteLine($"return result.Match<{outType}>(({callParams}) => {successExpr}, _ => fallback);");
            tw.Indent--;
            tw.WriteLine("}");
            tw.WriteLine();
            // Factory fallback
            tw.WriteLine($"public static async {taskKeyword}<{outType}> ValueOr<{genericIn}>(this {taskKeyword}<Result<{genericIn}>> awaitableResult, {fallbackFactoryType}) {constraints}");
            tw.WriteLine("{");
            tw.Indent++;
            tw.WriteLine("if (fallbackFactory is null) throw new System.ArgumentNullException(\"fallbackFactory\");");
            tw.WriteLine("var result = await awaitableResult.ConfigureAwait(false);");
            tw.WriteLine($"return result.Match<{outType}>(({callParams}) => {successExpr}, _ => fallbackFactory());");
            tw.Indent--;
            tw.WriteLine("}");
            tw.WriteLine();
        }
        tw.Indent--;
        tw.WriteLine("}");
        return SourceText.From(sw.ToString(), Encoding.UTF8);
    }

    public SourceText Generate()
    {
        using var sw = new StringWriter();
        using var tw = new IndentedTextWriter(sw);
        tw.WriteLine("// <auto-generated />");
        tw.WriteLine("#nullable enable");
        tw.WriteLine($"namespace {@namespace};");
        tw.WriteLine();
        tw.WriteLine("public static partial class ResultExtensions");
        tw.WriteLine("{");
        tw.Indent++;
        foreach (ushort arity in Enumerable.Range(1, maxOfParameters))
        {
            var genericIn = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"TValue{i}"));
            var constraints = string.Join(" ", Enumerable.Range(1, arity).Select(i => $"where TValue{i} : notnull"));
            var callParams = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"value{i}"));
            var outType = arity == 1 ? "TValue1" : $"({string.Join(", ", Enumerable.Range(1, arity).Select(i => $"TValue{i}"))})";
            var successExpr = arity == 1 ? "value1" : $"({callParams})";
            var fallbackParamType = arity == 1 ? "TValue1 fallback" : $"({string.Join(", ", Enumerable.Range(1, arity).Select(i => $"TValue{i}"))}) fallback";
            var fallbackFactoryType = arity == 1 ? "Func<TValue1> fallbackFactory" : $"Func<{outType}> fallbackFactory";
            // Constant fallback
            tw.WriteLine($"public static {outType} ValueOr<{genericIn}>(this Result<{genericIn}> result, {fallbackParamType}) {constraints}");
            tw.WriteLine("{");
            tw.Indent++;
            tw.WriteLine($"return result.Match<{outType}>(({callParams}) => {successExpr}, _ => fallback);");
            tw.Indent--;
            tw.WriteLine("}");
            tw.WriteLine();
            // Factory fallback
            tw.WriteLine($"public static {outType} ValueOr<{genericIn}>(this Result<{genericIn}> result, {fallbackFactoryType}) {constraints}");
            tw.WriteLine("{");
            tw.Indent++;
            tw.WriteLine("if (fallbackFactory is null) throw new System.ArgumentNullException(\"fallbackFactory\");");
            tw.WriteLine($"return result.Match<{outType}>(({callParams}) => {successExpr}, _ => fallbackFactory());");
            tw.Indent--;
            tw.WriteLine("}");
            tw.WriteLine();
        }
        tw.Indent--;
        tw.WriteLine("}");
        return SourceText.From(sw.ToString(), Encoding.UTF8);
    }
}

