// <auto-generated>
//     This code was generated by UnambitiousFx.Core.CodeGen.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#nullable enable

using UnambitiousFx.Core.Results.Reasons;

namespace UnambitiousFx.Core.Results.Reasons;

/// <summary>
/// Simple error class for testing purposes.
/// </summary>
public sealed record Error(string Message) : ErrorBase("TEST_ERROR", Message);
