// <auto-generated>
//     This code was generated by UnambitiousFx.Core.CodeGen.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#nullable enable

using UnambitiousFx.Core.OneOf;

namespace UnambitiousFx.Core.Tests.OneOf;

public sealed class OneOf8Tests
{
    [Fact]
    public void FromFirst_ShouldSetIsFirst() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromFirst(42);
        Assert.True(result.IsFirst);
        Assert.False(result.IsSecond);
        Assert.False(result.IsThird);
        Assert.False(result.IsFourth);
        Assert.False(result.IsFifth);
        Assert.False(result.IsSixth);
        Assert.False(result.IsSeventh);
        Assert.False(result.IsEighth);
    }
    
    [Fact]
    public void FromSecond_ShouldSetIsSecond() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromSecond("hello");
        Assert.False(result.IsFirst);
        Assert.True(result.IsSecond);
        Assert.False(result.IsThird);
        Assert.False(result.IsFourth);
        Assert.False(result.IsFifth);
        Assert.False(result.IsSixth);
        Assert.False(result.IsSeventh);
        Assert.False(result.IsEighth);
    }
    
    [Fact]
    public void FromThird_ShouldSetIsThird() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromThird(true);
        Assert.False(result.IsFirst);
        Assert.False(result.IsSecond);
        Assert.True(result.IsThird);
        Assert.False(result.IsFourth);
        Assert.False(result.IsFifth);
        Assert.False(result.IsSixth);
        Assert.False(result.IsSeventh);
        Assert.False(result.IsEighth);
    }
    
    [Fact]
    public void FromFourth_ShouldSetIsFourth() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromFourth(3.14);
        Assert.False(result.IsFirst);
        Assert.False(result.IsSecond);
        Assert.False(result.IsThird);
        Assert.True(result.IsFourth);
        Assert.False(result.IsFifth);
        Assert.False(result.IsSixth);
        Assert.False(result.IsSeventh);
        Assert.False(result.IsEighth);
    }
    
    [Fact]
    public void FromFifth_ShouldSetIsFifth() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromFifth(99.99m);
        Assert.False(result.IsFirst);
        Assert.False(result.IsSecond);
        Assert.False(result.IsThird);
        Assert.False(result.IsFourth);
        Assert.True(result.IsFifth);
        Assert.False(result.IsSixth);
        Assert.False(result.IsSeventh);
        Assert.False(result.IsEighth);
    }
    
    [Fact]
    public void FromSixth_ShouldSetIsSixth() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromSixth(1000L);
        Assert.False(result.IsFirst);
        Assert.False(result.IsSecond);
        Assert.False(result.IsThird);
        Assert.False(result.IsFourth);
        Assert.False(result.IsFifth);
        Assert.True(result.IsSixth);
        Assert.False(result.IsSeventh);
        Assert.False(result.IsEighth);
    }
    
    [Fact]
    public void FromSeventh_ShouldSetIsSeventh() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromSeventh('x');
        Assert.False(result.IsFirst);
        Assert.False(result.IsSecond);
        Assert.False(result.IsThird);
        Assert.False(result.IsFourth);
        Assert.False(result.IsFifth);
        Assert.False(result.IsSixth);
        Assert.True(result.IsSeventh);
        Assert.False(result.IsEighth);
    }
    
    [Fact]
    public void FromEighth_ShouldSetIsEighth() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromEighth(2.5f);
        Assert.False(result.IsFirst);
        Assert.False(result.IsSecond);
        Assert.False(result.IsThird);
        Assert.False(result.IsFourth);
        Assert.False(result.IsFifth);
        Assert.False(result.IsSixth);
        Assert.False(result.IsSeventh);
        Assert.True(result.IsEighth);
    }
    
    [InlineData(0)]
    [InlineData(42)]
    [InlineData(-1)]
    [Theory]
    public void FromFirst_ShouldStoreValue(int value) {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromFirst(value);
        Assert.True(result.First(out var extracted));
        Assert.Equal(value, extracted);
        Assert.False(result.Second(out _));
        Assert.False(result.Third(out _));
        Assert.False(result.Fourth(out _));
        Assert.False(result.Fifth(out _));
        Assert.False(result.Sixth(out _));
        Assert.False(result.Seventh(out _));
        Assert.False(result.Eighth(out _));
    }
    
    [InlineData("")]
    [InlineData("hello")]
    [InlineData("test string")]
    [Theory]
    public void FromSecond_ShouldStoreValue(string value) {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromSecond(value);
        Assert.True(result.Second(out var extracted));
        Assert.Equal(value, extracted);
        Assert.False(result.First(out _));
        Assert.False(result.Third(out _));
        Assert.False(result.Fourth(out _));
        Assert.False(result.Fifth(out _));
        Assert.False(result.Sixth(out _));
        Assert.False(result.Seventh(out _));
        Assert.False(result.Eighth(out _));
    }
    
    [Fact]
    public void FromThird_ShouldStoreValue() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromThird(true);
        Assert.True(result.Third(out var extracted));
        Assert.True(extracted);
        Assert.False(result.First(out _));
        Assert.False(result.Second(out _));
        Assert.False(result.Fourth(out _));
        Assert.False(result.Fifth(out _));
        Assert.False(result.Sixth(out _));
        Assert.False(result.Seventh(out _));
        Assert.False(result.Eighth(out _));
    }
    
    [Fact]
    public void FromFourth_ShouldStoreValue() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromFourth(3.14);
        Assert.True(result.Fourth(out var extracted));
        Assert.Equal(3.14, extracted);
        Assert.False(result.First(out _));
        Assert.False(result.Second(out _));
        Assert.False(result.Third(out _));
        Assert.False(result.Fifth(out _));
        Assert.False(result.Sixth(out _));
        Assert.False(result.Seventh(out _));
        Assert.False(result.Eighth(out _));
    }
    
    [Fact]
    public void FromFifth_ShouldStoreValue() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromFifth(99.99m);
        Assert.True(result.Fifth(out var extracted));
        Assert.Equal(99.99m, extracted);
        Assert.False(result.First(out _));
        Assert.False(result.Second(out _));
        Assert.False(result.Third(out _));
        Assert.False(result.Fourth(out _));
        Assert.False(result.Sixth(out _));
        Assert.False(result.Seventh(out _));
        Assert.False(result.Eighth(out _));
    }
    
    [Fact]
    public void FromSixth_ShouldStoreValue() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromSixth(1000L);
        Assert.True(result.Sixth(out var extracted));
        Assert.Equal(1000L, extracted);
        Assert.False(result.First(out _));
        Assert.False(result.Second(out _));
        Assert.False(result.Third(out _));
        Assert.False(result.Fourth(out _));
        Assert.False(result.Fifth(out _));
        Assert.False(result.Seventh(out _));
        Assert.False(result.Eighth(out _));
    }
    
    [Fact]
    public void FromSeventh_ShouldStoreValue() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromSeventh('x');
        Assert.True(result.Seventh(out var extracted));
        Assert.Equal('x', extracted);
        Assert.False(result.First(out _));
        Assert.False(result.Second(out _));
        Assert.False(result.Third(out _));
        Assert.False(result.Fourth(out _));
        Assert.False(result.Fifth(out _));
        Assert.False(result.Sixth(out _));
        Assert.False(result.Eighth(out _));
    }
    
    [Fact]
    public void FromEighth_ShouldStoreValue() {
        var result = OneOf<int, string, bool, double, decimal, long, char, float>.FromEighth(2.5f);
        Assert.True(result.Eighth(out var extracted));
        Assert.Equal(2.5f, extracted);
        Assert.False(result.First(out _));
        Assert.False(result.Second(out _));
        Assert.False(result.Third(out _));
        Assert.False(result.Fourth(out _));
        Assert.False(result.Fifth(out _));
        Assert.False(result.Sixth(out _));
        Assert.False(result.Seventh(out _));
    }
    
    [Fact]
    public void FromFirst_WhenMatchWithResponse_ShouldReturnFirstValue() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromFirst(42);
        var result = oneOf.Match(x => x, _ => { Assert.Fail("Second handler was called for OneOf holding First value"); return default; }, _ => { Assert.Fail("Third handler was called for OneOf holding First value"); return default; }, _ => { Assert.Fail("Fourth handler was called for OneOf holding First value"); return default; }, _ => { Assert.Fail("Fifth handler was called for OneOf holding First value"); return default; }, _ => { Assert.Fail("Sixth handler was called for OneOf holding First value"); return default; }, _ => { Assert.Fail("Seventh handler was called for OneOf holding First value"); return default; }, _ => { Assert.Fail("Eighth handler was called for OneOf holding First value"); return default; });
        Assert.Equal(42, result);
    }
    
    [Fact]
    public void FromSecond_WhenMatchWithResponse_ShouldReturnSecondValue() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromSecond("hello");
        var result = oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Second value"); return default; }, x => x, _ => { Assert.Fail("Third handler was called for OneOf holding Second value"); return default; }, _ => { Assert.Fail("Fourth handler was called for OneOf holding Second value"); return default; }, _ => { Assert.Fail("Fifth handler was called for OneOf holding Second value"); return default; }, _ => { Assert.Fail("Sixth handler was called for OneOf holding Second value"); return default; }, _ => { Assert.Fail("Seventh handler was called for OneOf holding Second value"); return default; }, _ => { Assert.Fail("Eighth handler was called for OneOf holding Second value"); return default; });
        Assert.Equal("hello", result);
    }
    
    [Fact]
    public void FromThird_WhenMatchWithResponse_ShouldReturnThirdValue() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromThird(true);
        var result = oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Third value"); return default; }, _ => { Assert.Fail("Second handler was called for OneOf holding Third value"); return default; }, x => x, _ => { Assert.Fail("Fourth handler was called for OneOf holding Third value"); return default; }, _ => { Assert.Fail("Fifth handler was called for OneOf holding Third value"); return default; }, _ => { Assert.Fail("Sixth handler was called for OneOf holding Third value"); return default; }, _ => { Assert.Fail("Seventh handler was called for OneOf holding Third value"); return default; }, _ => { Assert.Fail("Eighth handler was called for OneOf holding Third value"); return default; });
        Assert.True(result);
    }
    
    [Fact]
    public void FromFourth_WhenMatchWithResponse_ShouldReturnFourthValue() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromFourth(3.14);
        var result = oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Fourth value"); return default; }, _ => { Assert.Fail("Second handler was called for OneOf holding Fourth value"); return default; }, _ => { Assert.Fail("Third handler was called for OneOf holding Fourth value"); return default; }, x => x, _ => { Assert.Fail("Fifth handler was called for OneOf holding Fourth value"); return default; }, _ => { Assert.Fail("Sixth handler was called for OneOf holding Fourth value"); return default; }, _ => { Assert.Fail("Seventh handler was called for OneOf holding Fourth value"); return default; }, _ => { Assert.Fail("Eighth handler was called for OneOf holding Fourth value"); return default; });
        Assert.Equal(3.14, result);
    }
    
    [Fact]
    public void FromFifth_WhenMatchWithResponse_ShouldReturnFifthValue() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromFifth(99.99m);
        var result = oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Fifth value"); return default; }, _ => { Assert.Fail("Second handler was called for OneOf holding Fifth value"); return default; }, _ => { Assert.Fail("Third handler was called for OneOf holding Fifth value"); return default; }, _ => { Assert.Fail("Fourth handler was called for OneOf holding Fifth value"); return default; }, x => x, _ => { Assert.Fail("Sixth handler was called for OneOf holding Fifth value"); return default; }, _ => { Assert.Fail("Seventh handler was called for OneOf holding Fifth value"); return default; }, _ => { Assert.Fail("Eighth handler was called for OneOf holding Fifth value"); return default; });
        Assert.Equal(99.99m, result);
    }
    
    [Fact]
    public void FromSixth_WhenMatchWithResponse_ShouldReturnSixthValue() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromSixth(1000L);
        var result = oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Sixth value"); return default; }, _ => { Assert.Fail("Second handler was called for OneOf holding Sixth value"); return default; }, _ => { Assert.Fail("Third handler was called for OneOf holding Sixth value"); return default; }, _ => { Assert.Fail("Fourth handler was called for OneOf holding Sixth value"); return default; }, _ => { Assert.Fail("Fifth handler was called for OneOf holding Sixth value"); return default; }, x => x, _ => { Assert.Fail("Seventh handler was called for OneOf holding Sixth value"); return default; }, _ => { Assert.Fail("Eighth handler was called for OneOf holding Sixth value"); return default; });
        Assert.Equal(1000L, result);
    }
    
    [Fact]
    public void FromSeventh_WhenMatchWithResponse_ShouldReturnSeventhValue() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromSeventh('x');
        var result = oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Seventh value"); return default; }, _ => { Assert.Fail("Second handler was called for OneOf holding Seventh value"); return default; }, _ => { Assert.Fail("Third handler was called for OneOf holding Seventh value"); return default; }, _ => { Assert.Fail("Fourth handler was called for OneOf holding Seventh value"); return default; }, _ => { Assert.Fail("Fifth handler was called for OneOf holding Seventh value"); return default; }, _ => { Assert.Fail("Sixth handler was called for OneOf holding Seventh value"); return default; }, x => x, _ => { Assert.Fail("Eighth handler was called for OneOf holding Seventh value"); return default; });
        Assert.Equal('x', result);
    }
    
    [Fact]
    public void FromEighth_WhenMatchWithResponse_ShouldReturnEighthValue() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromEighth(2.5f);
        var result = oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Eighth value"); return default; }, _ => { Assert.Fail("Second handler was called for OneOf holding Eighth value"); return default; }, _ => { Assert.Fail("Third handler was called for OneOf holding Eighth value"); return default; }, _ => { Assert.Fail("Fourth handler was called for OneOf holding Eighth value"); return default; }, _ => { Assert.Fail("Fifth handler was called for OneOf holding Eighth value"); return default; }, _ => { Assert.Fail("Sixth handler was called for OneOf holding Eighth value"); return default; }, _ => { Assert.Fail("Seventh handler was called for OneOf holding Eighth value"); return default; }, x => x);
        Assert.Equal(2.5f, result);
    }
    
    [Fact]
    public void FromFirst_WhenMatch_ShouldCallFirstHandler() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromFirst(42);
        oneOf.Match(x => { Assert.Equal(42, x); }, _ => { Assert.Fail("Second handler was called for OneOf holding First value"); }, _ => { Assert.Fail("Third handler was called for OneOf holding First value"); }, _ => { Assert.Fail("Fourth handler was called for OneOf holding First value"); }, _ => { Assert.Fail("Fifth handler was called for OneOf holding First value"); }, _ => { Assert.Fail("Sixth handler was called for OneOf holding First value"); }, _ => { Assert.Fail("Seventh handler was called for OneOf holding First value"); }, _ => { Assert.Fail("Eighth handler was called for OneOf holding First value"); });
    }
    
    [Fact]
    public void FromSecond_WhenMatch_ShouldCallSecondHandler() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromSecond("hello");
        oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Second value"); }, x => { Assert.Equal("hello", x); }, _ => { Assert.Fail("Third handler was called for OneOf holding Second value"); }, _ => { Assert.Fail("Fourth handler was called for OneOf holding Second value"); }, _ => { Assert.Fail("Fifth handler was called for OneOf holding Second value"); }, _ => { Assert.Fail("Sixth handler was called for OneOf holding Second value"); }, _ => { Assert.Fail("Seventh handler was called for OneOf holding Second value"); }, _ => { Assert.Fail("Eighth handler was called for OneOf holding Second value"); });
    }
    
    [Fact]
    public void FromThird_WhenMatch_ShouldCallThirdHandler() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromThird(true);
        oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Third value"); }, _ => { Assert.Fail("Second handler was called for OneOf holding Third value"); }, x => { Assert.True(x); }, _ => { Assert.Fail("Fourth handler was called for OneOf holding Third value"); }, _ => { Assert.Fail("Fifth handler was called for OneOf holding Third value"); }, _ => { Assert.Fail("Sixth handler was called for OneOf holding Third value"); }, _ => { Assert.Fail("Seventh handler was called for OneOf holding Third value"); }, _ => { Assert.Fail("Eighth handler was called for OneOf holding Third value"); });
    }
    
    [Fact]
    public void FromFourth_WhenMatch_ShouldCallFourthHandler() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromFourth(3.14);
        oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Fourth value"); }, _ => { Assert.Fail("Second handler was called for OneOf holding Fourth value"); }, _ => { Assert.Fail("Third handler was called for OneOf holding Fourth value"); }, x => { Assert.Equal(3.14, x); }, _ => { Assert.Fail("Fifth handler was called for OneOf holding Fourth value"); }, _ => { Assert.Fail("Sixth handler was called for OneOf holding Fourth value"); }, _ => { Assert.Fail("Seventh handler was called for OneOf holding Fourth value"); }, _ => { Assert.Fail("Eighth handler was called for OneOf holding Fourth value"); });
    }
    
    [Fact]
    public void FromFifth_WhenMatch_ShouldCallFifthHandler() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromFifth(99.99m);
        oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Fifth value"); }, _ => { Assert.Fail("Second handler was called for OneOf holding Fifth value"); }, _ => { Assert.Fail("Third handler was called for OneOf holding Fifth value"); }, _ => { Assert.Fail("Fourth handler was called for OneOf holding Fifth value"); }, x => { Assert.Equal(99.99m, x); }, _ => { Assert.Fail("Sixth handler was called for OneOf holding Fifth value"); }, _ => { Assert.Fail("Seventh handler was called for OneOf holding Fifth value"); }, _ => { Assert.Fail("Eighth handler was called for OneOf holding Fifth value"); });
    }
    
    [Fact]
    public void FromSixth_WhenMatch_ShouldCallSixthHandler() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromSixth(1000L);
        oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Sixth value"); }, _ => { Assert.Fail("Second handler was called for OneOf holding Sixth value"); }, _ => { Assert.Fail("Third handler was called for OneOf holding Sixth value"); }, _ => { Assert.Fail("Fourth handler was called for OneOf holding Sixth value"); }, _ => { Assert.Fail("Fifth handler was called for OneOf holding Sixth value"); }, x => { Assert.Equal(1000L, x); }, _ => { Assert.Fail("Seventh handler was called for OneOf holding Sixth value"); }, _ => { Assert.Fail("Eighth handler was called for OneOf holding Sixth value"); });
    }
    
    [Fact]
    public void FromSeventh_WhenMatch_ShouldCallSeventhHandler() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromSeventh('x');
        oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Seventh value"); }, _ => { Assert.Fail("Second handler was called for OneOf holding Seventh value"); }, _ => { Assert.Fail("Third handler was called for OneOf holding Seventh value"); }, _ => { Assert.Fail("Fourth handler was called for OneOf holding Seventh value"); }, _ => { Assert.Fail("Fifth handler was called for OneOf holding Seventh value"); }, _ => { Assert.Fail("Sixth handler was called for OneOf holding Seventh value"); }, x => { Assert.Equal('x', x); }, _ => { Assert.Fail("Eighth handler was called for OneOf holding Seventh value"); });
    }
    
    [Fact]
    public void FromEighth_WhenMatch_ShouldCallEighthHandler() {
        var oneOf = OneOf<int, string, bool, double, decimal, long, char, float>.FromEighth(2.5f);
        oneOf.Match(_ => { Assert.Fail("First handler was called for OneOf holding Eighth value"); }, _ => { Assert.Fail("Second handler was called for OneOf holding Eighth value"); }, _ => { Assert.Fail("Third handler was called for OneOf holding Eighth value"); }, _ => { Assert.Fail("Fourth handler was called for OneOf holding Eighth value"); }, _ => { Assert.Fail("Fifth handler was called for OneOf holding Eighth value"); }, _ => { Assert.Fail("Sixth handler was called for OneOf holding Eighth value"); }, _ => { Assert.Fail("Seventh handler was called for OneOf holding Eighth value"); }, x => { Assert.Equal(2.5f, x); });
    }
    
    [Fact]
    public void ImplicitConversion_FromFirst_ShouldWork() {
        OneOf<int, string, bool, double, decimal, long, char, float> result = 42;
        Assert.True(result.IsFirst);
        Assert.True(result.First(out var value));
        Assert.Equal(42, value);
    }
    
    [Fact]
    public void ImplicitConversion_FromSecond_ShouldWork() {
        OneOf<int, string, bool, double, decimal, long, char, float> result = "hello";
        Assert.True(result.IsSecond);
        Assert.True(result.Second(out var value));
        Assert.Equal("hello", value);
    }
    
    [Fact]
    public void ImplicitConversion_FromThird_ShouldWork() {
        OneOf<int, string, bool, double, decimal, long, char, float> result = true;
        Assert.True(result.IsThird);
        Assert.True(result.Third(out var value));
        Assert.True(value);
    }
    
    [Fact]
    public void ImplicitConversion_FromFourth_ShouldWork() {
        OneOf<int, string, bool, double, decimal, long, char, float> result = 3.14;
        Assert.True(result.IsFourth);
        Assert.True(result.Fourth(out var value));
        Assert.Equal(3.14, value);
    }
    
    [Fact]
    public void ImplicitConversion_FromFifth_ShouldWork() {
        OneOf<int, string, bool, double, decimal, long, char, float> result = 99.99m;
        Assert.True(result.IsFifth);
        Assert.True(result.Fifth(out var value));
        Assert.Equal(99.99m, value);
    }
    
    [Fact]
    public void ImplicitConversion_FromSixth_ShouldWork() {
        OneOf<int, string, bool, double, decimal, long, char, float> result = 1000L;
        Assert.True(result.IsSixth);
        Assert.True(result.Sixth(out var value));
        Assert.Equal(1000L, value);
    }
    
    [Fact]
    public void ImplicitConversion_FromSeventh_ShouldWork() {
        OneOf<int, string, bool, double, decimal, long, char, float> result = 'x';
        Assert.True(result.IsSeventh);
        Assert.True(result.Seventh(out var value));
        Assert.Equal('x', value);
    }
    
    [Fact]
    public void ImplicitConversion_FromEighth_ShouldWork() {
        OneOf<int, string, bool, double, decimal, long, char, float> result = 2.5f;
        Assert.True(result.IsEighth);
        Assert.True(result.Eighth(out var value));
        Assert.Equal(2.5f, value);
    }
    
}
