name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'releases/*'
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.props'
      - '**.sln'
      - '**.slnx'
      - '.github/workflows/qodana_code_quality.yml'
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.props'
      - '**.sln'
      - '**.slnx'
      - '.github/workflows/qodana_code_quality.yml'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  qodana:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1914918270 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'