// <auto-generated>
//     This code was generated by UnambitiousFx.Core.CodeGen.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#nullable enable

using System.Diagnostics.CodeAnalysis;

namespace UnambitiousFx.Core.OneOf;

internal sealed class FirstOneOf<TFirst, TSecond> : OneOf<TFirst, TSecond>
    where TFirst : notnull
    where TSecond : notnull
{
    private readonly TFirst _first;
    
    public FirstOneOf(TFirst first) {
        _first = first;
    }
    
    public override bool IsFirst => true;
    public override bool IsSecond => false;
    
    public override TOut Match<TOut>(Func<TFirst, TOut> firstFunc, Func<TSecond, TOut> secondFunc) {
        return firstFunc(_first);
    }
    
    public override void Match(Action<TFirst> firstAction, Action<TSecond> secondAction) {
        firstAction(_first);
    }
    
    public override bool First([NotNullWhen(true)] out TFirst? first) {
        first = _first;
        return true;
    }
    
    public override bool Second([NotNullWhen(true)] out TSecond? second) {
        second = default;
        return false;
    }
    
}
